# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-05 04:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_website'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='rating',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
